TrajectoryPlannerROS:
    max_vel_x: 2
    # acc_lim_x: 2
    # acc_lim_theta: 2
    # max_vel_theta: 2
    # min_vel_theta: -2
    # min_in_place_vel_theta: 0.8
    # footprint: [[0.2, 0.2], [0.2, 0.2]]
    robot_radius: 0.37

    # pdist_scale: 2
    # occdist_scale: 0.1
    # heading_lookahead: 1

    # controller_frequency: 50

    holonomic_robot: false
